version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'
  e2e-tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.35.0-focal
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Playwright E2E Tests
          command: npx playwright test
workflows:
  build-and-test:
    jobs:
      - test-node
      - e2e-tests
    # - deploy:
    #     requires:
    #       - test-node